services:
    db:
      image: "mcr.microsoft.com/mssql/server:2022-latest"
      environment:
          SA_PASSWORD: S3cur3P@ssW0rd!
          ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"
      networks:
        - app-network
      # volumes:
      #   - ./sql-scripts:/docker-entrypoint-initdb.d
      #   - ./path/to/host/certificates:/var/opt/mssql/security/ca-certificates
      # command: >
      #   /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30s & /docker-entrypoint-initdb.d/init-database.sh"

    api: 
      image : nkosanan/asset-tracking #your-docker-repo/your-aspnet-core-api
      build:
        context: .
        dockerfile: Dockerfile
      environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection= ;Database=ItemManagementSystem;User Id=sa;Password=S3cur3P@ssW0rd!;TrustServerCertificate=True
      ports:
          - "8082:80"
      depends_on:
        - db
      networks:
      - app-network

networks:
  app-network:
    driver: bridge     