services:
    db:
      image: "mcr.microsoft.com/mssql/server:2022-latest"
      environment:
          SA_PASSWORD: S3cur3P@ssW0rd!
          ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"
      healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -Q 'SELECT 1'"]
        interval: 10s  # Check every 10 seconds
        timeout: 5s    # Timeout after 5 seconds
        retries: 10     # Retry up to 10 times
        start_period: 30s  # Start the health check after 30 seconds
      volumes:
        - sql_data:/var/opt/mssql
    
    api: 
      image : nkosanan/asset-tracking #your-docker-repo/your-aspnet-core-api
      build:
        context: .
        dockerfile: Dockerfile
      environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8000
      - ConnectionStrings__DefaultConnection=Server=db;Database=ItemManagementSystem;User Id=sa;Password=S3cur3P@ssW0rd!;TrustServerCertificate=True
      ports:
          - "8000:8000"
      depends_on:
         db:
          condition: service_healthy  # Only start when the db service is healthy

volumes:
  sql_data:      