apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-management-api-deployment
  labels:
    app: item-management-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-management-api
  template:
    metadata:
      labels:
        app: item-management-api 
    spec:
      containers:
        - name: item-management-api
          image: nkosanan/item-management:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80       
          env:
            - name: ConnectionStrings
              valueFrom:
                secretKeyRef:
                  name: secret-sqlserver
                  key: ConnectionStrings
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: item-management-api-svc
spec:
  type: LoadBalancer
  selector:
    app: item-management-api
  ports:
    - protocol: TCP
      port: 80
