apiVersion: v1
kind: Secret
metadata:
  name: secret-sqlserver
type: Opaque
stringData:
  ConnectionStrings: "Server=sqlserver-svc; Database=IrepoM; User Id=sa; Password=S3cur3P@ssW0rd!;TrustServerCertificate=True;MultipleActiveResultSets=true" 
  Password: "S3cur3P@ssW0rd!"