FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Item.API/Item.API.csproj", "Item.API/"]
COPY ["Item.Application/Item.Application.csproj", "Item.Application/"]
COPY ["Item.DataAccess/Item.DataAccess.csproj", "Item.DataAccess/"]
COPY ["Item.Domain/Item.Domain.csproj", "Item.Domain/"]
RUN dotnet restore "./Item.API/Item.API.csproj"
COPY . .
WORKDIR "/src/Item.API"
RUN dotnet build "./Item.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Item.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Item.API.dll"]